-- begin INSTRUMENT1_PROPOSAL_DATA
alter table INSTRUMENT1_PROPOSAL_DATA add constraint FK_INSTRUMENT1_PROPOSAL_DATA_ON_PROPOSAL foreign key (PROPOSAL_ID) references PROPOSALS_PROPOSAL(ID)^
create index IDX_INSTRUMENT1_PROPOSAL_DATA_ON_PROPOSAL on INSTRUMENT1_PROPOSAL_DATA (PROPOSAL_ID)^
-- end INSTRUMENT1_PROPOSAL_DATA
